services:
  auto-claimer:
    image: ftso-fee-claimer
    env_file: .env
    volumes:
      - ./src:/app/src
    command: yarn auto-claimer
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cli:
    image: ftso-fee-claimer
    env_file: .env
    volumes:
      - ./src:/app/src
    entrypoint: ["yarn", "cli"]
    extra_hosts:
      - "host.docker.internal:host-gateway"