services:
  auto-claimer:
    image: ftso-fee-claimer
    env_file: .env
    volumes:
      - ./src:/app/src
    command: yarn auto-claimer

  cli:
    image: ftso-fee-claimer
    env_file: .env
    volumes:
      - ./src:/app/src
    entrypoint: ["yarn", "cli"]
    profiles: ["cli"]